name: simple-linked-list
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./simple-linked-list
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./simple-linked-list
        run: cargo test --verbose
